### ISSUE TITLE
Fails on validating connection string because underlying library doesn't support it

### ISSUE THREAD

**Issue by Szer** [fsprojects/AzureStorageTypeProvider#117] opened 2018-11-16 11:40 UTC
### Description

Just use 2.0.0-beta with any connection string.
Type providers tries to validate connection string here by checking table exists
https://github.com/fsprojects/AzureStorageTypeProvider/blob/83bf546b5983d12e6b80d0297b00502a15d81e65/src/FSharp.Azure.StorageTypeProvider/Configuration.fs#L50

But fails horribly because Tables are not supported by WindowsAzure.Storage
https://github.com/Azure/azure-storage-net
Quote:
`As of 9.4.0, Tables are not supported by this library.`

### Repro steps

Please provide the steps required to reproduce the problem

type BlobType = AzureTypeProvider<accountName = "DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx;BlobEndpoint=https://xxx.blob.core.windows.net/;">

### Expected behavior

It should compile

### Actual behavior

Please provide a description of the actual behavior you observe. 
![image](https://user-images.githubusercontent.com/10308233/48619232-e1fe8280-e9ac-11e8-9af2-e4b42c128573.png)

**Comment by isaacabraham** [comment] 2018-11-18 16:44
Oh great. A fat breaking change. There's already some work I've done to support blob only accounts so it might not be so bad but I'm wondering what the solution for tables will be going forward.

**Comment by isaacabraham** [comment] 2018-11-18 16:46
Looking at this error message are you sure that's actually not the problem here - that you've created a blob only storage account? If so there's another issue to sort that out, I'll make that part of the next release.

**Comment by Szer** [comment] 2018-11-19 11:52
@isaacabraham, yes, you right, it is blob-only storage account :) Anyway, beware about WindowsAzure.Storage!

**Comment by isaacabraham** [comment] 2018-11-19 13:56
OK - I'm going to close this since it's a duplicate of #110 - I want to get that working next :-)

**Closed by isaacabraham** 2018-11-19 13:56 UTC

**Comment by isaacabraham** [comment] 2018-11-24 18:51
@Szer there's a build [here](https://ci.appveyor.com/project/fsprojectsgit/azurestoragetypeprovider/builds/20527791/artifacts) that you can try.

**Comment by Szer** [comment] 2018-11-28 08:39
@isaacabraham it works! Thanks :D

**Comment by isaacabraham** [comment] 2018-11-28 08:45
Excellent - thanks for confirming! It still shows the Tables and Queues properties, but they will never show anything - not ideal but it works. I'll push out a full 2.0 release this week with it in :-)
